services:
  url_shortener:
    build: .
    container_name: url_shortener
    ports:
      - "8083:8083"
    restart: always
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev_two
